sudo: required
language: rust
compiler: gcc
cache: cargo

notifications:
  email: false

rust:
  - stable

os:
  - linux

branches:
  only:
    - travis

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libgtk-3-dev
    - libgtk-3-0
    - gcc-6
    - g++-6
    - libstdc++6


before_install:
  - curl -so "$TRAVIS_BUILD_DIR/libsciter-gtk-64.so" https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.gtk/libsciter-gtk-64.so

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi
  - export PATH="$PATH:$TRAVIS_BUILD_DIR"
  - export LIBRARY_PATH="$LIBRARY_PATH:$TRAVIS_BUILD_DIR"
  - export RUST_BACKTRACE=1
  - ls /usr/lib/x86_64-linux-gnu/libstdc++*
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - gcc --version
  - gcc-6 --version
