sudo: false
language: rust
cache: cargo

rust:
  - stable

os:
  - linux

branches:
  only:
    - travis

addons:
  apt:
    packages:
    - gcc-6
    - g++-6
    - libgtk-3-dev

env:
  - GTK=3.4
  - GTK=3.18

before_install:
  - curl -so "$TRAVIS_BUILD_DIR/libsciter-gtk-64.so" https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin.gtk/libsciter-gtk-64.so

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR"; fi
  - export PATH="$PATH:$TRAVIS_BUILD_DIR"
  - export LIBRARY_PATH="$LIBRARY_PATH:$TRAVIS_BUILD_DIR"
  - export RUST_BACKTRACE=1
